- name: config db
  hosts: db
  become: yes
  vars:
    login_host: db.navaneeth.cloud
  vars_prompt:
  - name: mysql_root_password
    prompt: please enter mysql password
    private: no
  tasks:
  - name: install mysql
    ansible.builtin.dnf:
      name: mysql
      state: latest
  - name: enable mysql
    ansible.builtin.service:
      name: start mysqql
      status: started
      enabled: yes

  - name: install mysql python dependencies
    ansible.builtin.pip:
      name:
      - PyMySQL
      - cryptography
      executable: pip3.9

  - name: check DB connection
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{mysql_root_password}}"
      login_host: "{{local_host}}"    
      filter: version
    ignore_errors: yes
    register: mysql_connection_output

  - name: print output
    ansible.builtin.debug:
     msg: "Output: {{mysql_connection_output}}"  

  - name: setup root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
    when: mysql_connection_output.failed is true # don't give {{ }} in when condition

