- name: config backend
  hosts: backend
  become: yes
  vars:

  tasks:
  - name : disable nodejs 
    ansible.builtin.command: dnf module disable nodejs -y
    
  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y
  

  - name : install nodejs
    ansible.builtin.dnf: 
      name:  nodejs
      state: installed

  - name: add user expense
    ansible.builtin.user: 
      name: expense
  - name: creeate app directory
    ansible.builtin.file:
     dest: /app
     state: directory
  - name: Download the application code to created app directory.
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: temp/app

  - name: Unzip backend app code
    ansible.builtin.unarchive:
    src: /tmp/backend.zip
    dest: /app
    

    


