- name: configuring db server
  hosts: db
  become: yes
  vars:
    local_host: db.navaneeth.cloud
  vars_prompt:
  - name: mysql_root_password
    prompt: please enter mysql password
    private: no
  tasks:
  - name: install mysql server
    ansible.bultin.dnf:
      name: mysql
      state: latest

  - name: start and enable mysql
    ansible.builtin.service:
    status: started
    enabled: yes

  - name: install python mysql dependencies
    ansible.builtin.pip:
      name:
      - PyMySQL
      - cryptography
      executable: pip3.9

 # check password is already setup or not
  - name: check DB connection
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{mysql_root_password}}"
      login_host: "{{login_host}}"
      filter: version
    ignore_errors: yes  
    register: mysql_connection_output
  - name: print output
    ansible.builtin.debug:
      msg: "Output: {{mysql_connection_output}}"  

  - name: setup root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
    when: mysql_connection_output.failed is tru    