- name: config frontend
  hosts: frontend
  become: yes
  tasks:
  - name:  Install Nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name : Startr & Enable nginx
    ansible.builtin.service:
      name:  nginx
      state: started
      enabled: yes

  # - name: start and enable nginx
  #   ansible.builtin.service:
  #     name: nginx
  #     state: started
  #     enabled: yes

